### ISSUE TITLE
RuntimeError: The size of tensor a (577) must match the size of tensor b (257) at non-singleton dimension 1

### ISSUE THREAD

**Issue by HarrySSH** [llava-rlhf/LLaVA-RLHF#11]
Thanks for the previous explanation. I encountered another bug here.

_File "/.../anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 200, in forward
    embeddings = embeddings + self.position_embedding(self.position_ids)
RuntimeError: The size of tensor a (577) must match the size of tensor b (257) at non-singleton dimension 1_

I used the standard dataset, and model to train the RL pipeline, just to make sure I can get it running. what do you think can be the issue to cause this bug?

Many thanks

**Comment by HarrySSH** [comment]
Thanks for your help!
I am using  
[train_rl_model.sh](https://github.com/llava-rlhf/LLaVA-RLHF/blob/main/RLHF/scripts/7b-v1.5-224/train_rl_model.sh)

**Comment by Edward-Sun** [comment]
Did you run the first two steps of RLHF, i.e., reward model training and RL model initialization?

**Comment by HarrySSH** [comment]
> Did you run the first two steps of RLHF, i.e., reward model training and RL model initialization?

Yes! That's the reason I felt quite confused. :) 
the reward model is in the 13b and the model init is in the 7b
And the final train_rl_model.sh is in the 7b folder

**Comment by Edward-Sun** [comment]
**Note**: For both 7b and 13b policy models, we use the same 13b reward model.

If you have done the 7b initialization, I will double-check the script.

**Comment by HarrySSH** [comment]
And for your information. I tried to change the position embedding directly on the embedding features on the dimension one,  and meaning performance position embedding directly based on the dimension of the embedding instead of the inputs_ids.
 And then I get this error "embeddings = embeddings + position_ids
RuntimeError: The size of tensor a (1024) must match the size of tensor b (577) at non-singleton dimension 2"

Not sure if this is an useful information though

**Comment by HarrySSH** [comment]
> **Note**: For both 7b and 13b policy models, we use the same 13b reward model.
> 
> If you have done the 7b initialization, I will double-check the script.

Yes. You made that very clear on the readMe :) I think I followed that part

**Comment by Edward-Sun** [comment]
> RuntimeError: The size of tensor a (577) must match the size of tensor b (257) at non-singleton dimension 1

I think you don't need to change the code. 577 = 24^2 + 1, and 256 = 16^2 +1.

[clip-vit-large-patch14-336](https://huggingface.co/openai/clip-vit-large-patch14-336) used 336 / 14 = 24 patches for each dimension, while [clip-vit-large-patch14](https://huggingface.co/openai/clip-vit-large-patch14) used 224 / 14 = 16. So the problem is the loaded checkpoint is not the same as the one in the configuration.

**Comment by HarrySSH** [comment]
ah thank you so much!

**Comment by HarrySSH** [comment]
I found the issue. In the script 7b initialization,  it used the openai/clip-vit-large-patch14,

but the reward function in the 13b use VISION_TOWER=openai/clip-vit-large-patch14-336

I guess that's where the bug happened

**Comment by Edward-Sun** [comment]
Hi, the use of different vision modules is by design. I will rerun the script and see whether I can reproduce the bug. Thank you for your patience.

**Comment by HarrySSH** [comment]
Ah ! I am not saying what you wrote is incorrect, I just mean there are inconstant to each other and that's totally me misinterpreted your codes! I am retraining the reward function with the other clip model and I will let you know if my issue is resolved.

**Comment by Edward-Sun** [comment]
Hi Harry,

I have checked the code and the issue seems that in the [cleaned script](https://github.com/llava-rlhf/LLaVA-RLHF/blob/9f5b4ca36406d3303a9ffd19bb188e889bfea469/RLHF/scripts/7b-v1.5-224/train_rl_model.sh#L15),  the wrong base models are used for the policy and the reward model. The correct version should be:
```bash
POLICY_BASE_MODEL_NAME=LLaVA-RLHF-7b-v1.5-224/sft_model
RM_BASE_MODEL_NAME=LLaVA-RLHF-13b-v1.5-336/sft_model
```
The script is updated.

Also, one issue I found while re-running our public codebase is that `transformers==4.31.0` should be used instead of `transformers==4.33.0`, otherwise, it would cause a length mismatch issue due to the inconsistency of the tokenizer implementation in the transformers package.

Sorry for the inconvenience.
