### ISSUE TITLE
Training on RTX 4090

### ISSUE THREAD

**Issue by luohaowen2003** [llava-rlhf/LLaVA-RLHF#18]
Thank you for your awesome work!

I wonder if it's possible to train the reward model and initialize the policy model on a node with 8 RXT 4090 GPU?

I found that the PPO process can be run with `train_rl_model.sh` under such setting, but when training the RM with `train_reward_model.sh` or initializing the policy model with `initialize_policy_model.sh`, I will run out of memory, which seems weird to me as the PPO process is presumably more demanding.

I've tried to minimize the `per_device_train_batch_size` to 1 but still run into such issue.

Thank you!

**Comment by Edward-Sun** [comment]
Hi,
This is because we accidentally used [QLoRA (4-bit base weights)](https://github.com/llava-rlhf/LLaVA-RLHF/blob/830a083fd83e607da3c35f2e6aef833523c1e722/RLHF/models/ppo_trainer.py#L976) during PPO but used 16-bit for sft/rm. You might be able to train the RM or initialize the policy model with [4-bit](https://github.com/llava-rlhf/LLaVA-RLHF/blob/830a083fd83e607da3c35f2e6aef833523c1e722/RLHF/finetune_lora_sft_ds.py#L159C5-L159C9) as well.

**Comment by luohaowen2003** [comment]
Thanks！

**Comment by Winsome-A** [comment]
I wonder if it's possible to train the reward model and initialize the policy model on a node with only 4  RXT 4090 GPUs? not 8
